"""Visualize real trajectories or schema-faithful synthetic fixtures."""

from __future__ import annotations

# Do not export a ``collect`` function that would shadow the submodule.
from method.visualization.collect import (
    Collection,
    Run,
    collect_group,
    delta_p_0_lookup,
    hysteresis_frame,
    projection_frame,
)
from method.visualization.decay import (
    current_probe_drift_frame,
    decay_frame,
    fit_frame,
    latent_frame,
    mechanism_frame,
    phase_contrast_frame,
    probe_drift_frame,
    realignment_pairs,
    validation_frame,
)
from method.visualization.figures import (
    decay_scatter_grid,
    drift_line,
    forecast_grid,
    headline_curves,
    hysteresis_bar,
    line_with_band,
    mechanism_grid,
    overlay_grid,
    phase_contrast,
    pooled_correlation_summary,
    recalibration_grid,
    scatter_metric_grid,
    scatter_projection_correlation,
    scatter_validation,
)
from method.visualization.forecast import (
    baseline_fits,
    gain_frame,
    prediction_frame,
    score_frame,
    score_table,
)
from method.visualization.labels import display_dataset_name
from method.visualization.schema import (
    StepRecord,
    Trajectory,
    delta_p_by_dataset,
    load_trajectory,
    load_trajectory_set,
    metric_pairs,
    projection_pairs,
    to_frame,
    z_component_matrix,
)
from method.visualization.style import PLOTS_DIR, apply_style, save_figure

__all__ = [
    "PLOTS_DIR",
    "Collection",
    "Run",
    "StepRecord",
    "Trajectory",
    "apply_style",
    "baseline_fits",
    "collect_group",
    "current_probe_drift_frame",
    "decay_frame",
    "decay_scatter_grid",
    "delta_p_0_lookup",
    "delta_p_by_dataset",
    "hysteresis_frame",
    "fit_frame",
    "forecast_grid",
    "gain_frame",
    "headline_curves",
    "latent_frame",
    "mechanism_frame",
    "mechanism_grid",
    "overlay_grid",
    "phase_contrast",
    "phase_contrast_frame",
    "pooled_correlation_summary",
    "prediction_frame",
    "probe_drift_frame",
    "recalibration_grid",
    "projection_frame",
    "realignment_pairs",
    "score_frame",
    "score_table",
    "display_dataset_name",
    "drift_line",
    "hysteresis_bar",
    "line_with_band",
    "load_trajectory",
    "load_trajectory_set",
    "metric_pairs",
    "projection_pairs",
    "save_figure",
    "scatter_metric_grid",
    "scatter_projection_correlation",
    "scatter_validation",
    "to_frame",
    "validation_frame",
    "z_component_matrix",
]
